services:
  postgres:
    image: postgres:17.7-alpine3.23
    container_name: db-proffy
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - proffy

  api-proffy:
    build:
      context: .
    container_name: api-proffy
    restart: always
    command: sh -c "npm run db:migrate"
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - API_BASE_URL=http://localhost:3333
      - JWT_TOKEN=${JWT_TOKEN}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - proffy

networks:
  proffy:
    driver: bridge

volumes:
  db:
