services:
  postgres:
    image: postgres:17
    container_name: api_proffy
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proffy_database
    ports:
      - "5432:5432"
    volumes:
      - proffy_data:/var/lib/postgresql/data

volumes:
  proffy_data: