name: GIRHUB-CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest
    environment: 'staging'
    outputs:
      sha: ${{ steps.generate_sha.outputs.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Build docker image
        run: docker build -t santosfael/api-proffy:${{ steps.generate_sha.outputs.sha }} .
      
      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push docker image
        run: |
          docker push santosfael/api-proffy:${{ steps.generate_sha.outputs.sha }}
          docker tag santosfael/api-proffy:${{ steps.generate_sha.outputs.sha }} santosfael/api-proffy:latest
          docker push santosfael/api-proffy:latest

  deploy:
    runs-on: ubuntu-latest
    name: "Deploy"
    environment: 'staging'
    needs: [build-and-push]
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v6
        with:
          repository: Santosfael/helm-files
          branch: main
          path: .
          token: ${{ secrets.TOKEN_GITHUB }} 

      - name: Update value.yaml in Helm repo
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'proffy/values.yaml'
          propertyPath: 'image.tag'
          value: "${{ needs.build-and-push.outputs.sha }}"
          repository: Santosfael/helm-files
          branch: main
          token: ${{ secrets.TOKEN_GITHUB }}
          commitChange: true
          message: 'Update image tag to ${{ needs.build-and-push.outputs.sha }}'


